# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY.
_commit: v0.1.2
_src_path: git@github.com:theoryzhenkov/repo_template.base.git
github_owner: theoryzhenkov
license_holder: theor
license_year: '2026'
project_description: ''
project_name: home-theor-net
